= Data types fabric (dtFabric) format specification

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

Data types fabric (dtFabric) is a proof-of-concept YAML-based definition
language to specify format and data types.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | Data types fabric (dtFabric) format specification
| Classification: | Public
| Keywords: | dtFabric
|===

[preface]
== License

....
Copyright (C) 2016-2019, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | November 2016 | Initial version.
| 0.0.2 | J.B. Metz | March 2017 | Moved documentation to asciidoc.
| 0.0.3 | J.B. Metz | March 2017 | Worked on documentation.
| 0.0.4 | J.B. Metz | April 2017 | Worked on documentation.
| 0.0.5 | J.B. Metz | April 2017 | Worked on documentation.
| 0.0.6 | J.B. Metz | May 2017 | Worked on documentation.
| 0.0.7 | J.B. Metz | October 2017 | Worked on documentation.
| 0.0.8 | J.B. Metz | April 2019 | Worked on documentation.
|===

:numbered:
== Overview

Data types fabric (dtFabric) is a proof-of-concept YAML-based definition
language to specify format and data types.

* storage data types, such as integers, characters, structures
* semantic data types, such as constants, enumerations
* layout data types, such as format, vectors, trees

== [[data_type_definition]]Data type definition

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| aliases | List of strings | No | List of alternative names for the data type
| description | string | No | Description of the data type
| name | string | Yes | Name of the data type
| type | string | Yes | Definition type +
See section: <<data_type_definition_types,Data type definition types>>
| urls | List of strings | No | List of URLS that contain more information about the data type
|===

=== [[data_type_definition_types]]Data type definition types

[cols="1,5",options="header"]
|===
| Identifier | Description
| boolean | Boolean
| character | Character
| constant | Constant
| enumeration | Enumeration
| floating-point | Floating-point
| format | Data format metadata +
See section: <<data_format,Data format>>
| integer | Integer
| padding | Alignment padding, only supported as a member definition of a structure data type
| stream | Stream
| string | String
| structure | Structure
| structure-family | [yellow-background]*TODO: describe*
| union | Union data type
| uuid | UUID (or GUID)
|===

[yellow-background]*TODO: consider adding the following types*

[cols="1,5",options="header"]
|===
| Identifier | Description
| bit-field | Bit field (or group of bits)
| fixed-point | Fixed-point data type
| reference | [yellow-background]*TODO*
|===

== Storage data types

Storage data types are data types that represent stored (or serialized) values.
In addition to the <<data_type_definition,Data type definition attributes>>
storage data types also define:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| attributes | mapping | No | Data type attributes +
See section: <<storage_data_type_definition_attributes,Storage data type definition attributes>>
|===

=== [[storage_data_type_definition_attributes]]Storage data type definition attributes

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| byte_order | string | No | Byte-order of the data type +
Valid options are: "big-endian", "little-endian", "native" +
The default is native
|===

[NOTE]
middle-endian is a valid byte-ordering but currently not supported.

=== Fixed-size data types

In addition to the <<storage_data_type_definition_attributes,Storage data type definition attributes>>
fixed-size data types also define the following attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| size | integer or string | No | size of data type in number of units or "native" if architecture dependent +
The default is "native"
| units | string | No | units of the size of the data type +
The default is bytes
|===

==== Boolean

A boolean is a data type to represent true-or-false values.

[source,yaml]
----
name: bool32
aliases: [BOOL]
type: boolean
description: 32-bit boolean type
attributes:
  size: 4
  units: bytes
  false_value: 0
  true_value: 1
----

Boolean data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| false_value | integer | No | Integer value that represents False +
The default is 0
| true_value | integer | No | Integer value that represents True +
The default is not-set, which represent any value except for the false_value
|===

Currently supported size attribute values are: 1, 2 and 4 bytes.

==== Character

A character is a data type to represent elements of textual strings.

[source,yaml]
----
name: wchar16
aliases: [WCHAR]
type: character
description: 16-bit wide character type
attributes:
  size: 2
  units: bytes
----

Currently supported size attribute values are: 1, 2 and 4 bytes.

==== Fixed-point

A fixed-point is a data type to represent elements of fixed-point values.

[yellow-background]*TODO: add example*

==== Floating-point

A floating-point is a data type to represent elements of floating-point values.

[source,yaml]
----
name: float64
aliases: [double, DOUBLE]
type: floating-point
description: 64-bit double precision floating-point type
attributes:
  size: 8
  units: bytes
----

Currently supported size attribute values are: 4 and 8 bytes.

==== Integer

An integer is a data type to represent elements of integer values.

[source,yaml]
----
name: int32le
aliases: [LONG, LONG32]
type: integer
description: 32-bit little-endian signed integer type
attributes:
  byte_order: little-endian
  format: signed
  size: 4
  units: bytes
----

Integer data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| format | string | No | Signed or unsiged +
The default is signed
|===

Currently supported size attribute values are: 1, 2, 4 and 8 bytes.

==== UUID (or GUID)

An UUID (or GUID) is a data type to represent a Globally or Universal unique
identifier (GUID or UUID) data types.

[source,yaml]
----
name: known_folder_identifier
type: uuid
description: Known folder identifier.
attributes:
  byte_order: little-endian
----

Currently supported size attribute values are: 16 bytes.

=== Variable-sized data types

==== Sequence

A sequence is a data type to represent a sequence of individual elements such
as an array of integers.

[source,yaml]
----
name: page_numbers
type: sequence
description: Array of 32-bit page numbers.
element_data_type: int32
number_of_elements: 32
----

Sequence data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| element_data_type | string | Yes | Data type of sequence element
| elements_data_size | integer or string | See note | Integer value or expression to determine the data size of the elements in the sequence
| elements_terminator | integer | See note | element value that indicates the end-of-string
| number_of_elements | integer or string | See note | Integer value or expression to determine the number of elements in the sequence
|===

[NOTE]
One of the elements attributes: "elements_data_size", "elements_terminator"
or "number_of_elements" must be set.

[yellow-background]*TODO: describe expressions and the map context*

==== Stream

A stream is a data type to represent a continous sequence of elements such as
a byte stream.

[source,yaml]
----
name: data
type: stream
element_data_type: byte
number_of_elements: data_size
----

Stream data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| element_data_type | string | Yes | Data type of stream element
| elements_data_size | integer or string | See note | Integer value or expression to determine the data size of the elements in the stream
| elements_terminator | integer | See note | element value that indicates the end-of-string
| number_of_elements | integer or string | See note | Integer value or expression to determine the number of elements in the stream
|===

[NOTE]
One of the elements attributes: "elements_data_size", "elements_terminator"
or "number_of_elements" must be set.

[yellow-background]*TODO: describe expressions and the map context*

==== String

A string is a data type to represent a continous sequence of elements with a
known encoding such as an UTF-16 formatted string.

[source,yaml]
----
name: utf16le_string_with_size
type: string
ecoding: utf-16-le
element_data_type: wchar16
elements_data_size: string_data_size
----

[source,yaml]
----
name: utf16le_string_with_terminator
type: string
ecoding: utf-16-le
element_data_type: wchar16
elements_terminator: "\x00\x00"
----

String data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| encoding | string | Yes | Encoding of the string
| element_data_type | string | Yes | Data type of string element
| elements_data_size | integer or string | See note | Integer value or expression to determine the data size of the elements in the string
| elements_terminator | integer | See note | element value that indicates the end-of-string
| number_of_elements | integer or string | See note | Integer value or expression to determine the number of elements in the string
|===

[NOTE]
One of the elements attributes: "elements_data_size", "elements_terminator"
or "number_of_elements" must be set.

[yellow-background]*TODO: describe elements_data_size and number_of_elements expressions and the map context*

=== Storage data types with members

In addition to the <<storage_data_type_definition_attributes,Storage data type definition attributes>>
storage data types with member also define the following attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| members | list | Yes | List of member definitions +
See section: <<member_definition,Member definition>>
|===

==== [[member_definition]]Member definition

A member definition supports the following attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| aliases | List of strings | No | List of alternative names for the member
| condition | string | No | Condition under which the member is condisidered to be present
| data_type | string | See note | Name of the data type definition of the member
| description | string | No | Description of the member
| name | string | See note | Name of the member
| type | string | See note | Name of the definition type of the member +
See section: <<data_type_definition_types,Data type definition types>>
| value | integer or string | See note | Supported value
| values | List of integers or strings | See note | Supported values
|===

[NOTE]
The name attribute: "name" must be set for storage data types with members
except for the Union type where it is optional.

[NOTE]
One of the type attributes: "data_type" or "type" must be set. The following
definition types cannot be directly defined as a member definition: "constant",
"enumeration", "format" and "structure".

[yellow-background]*TODO: describe member definition not supporting attributes.*

[NOTE]
Both the value attributes: "value" and "values" are optional but only one is
supported at a time.

[yellow-background]*TODO: describe conditions*

==== Structure

A structure is a data type to represent a composition of members of other
data types.

[yellow-background]*TODO: add structure size hint?*

[source,yaml]
----
name: point3d
aliases: [POINT]
type: structure
description: Point in 3 dimensional space.
attributes:
  byte_order: little-endian
members:
- name: x
  aliases: [XCOORD]
  data_type: int32
- name: y
  data_type: int32
- name: z
  data_type: int32
----

[source,yaml]
----
name: sphere3d
type: structure
description: Sphere in 3 dimensional space.
members:
- name: number_of_triangles
  data_type: int32
- name: triangles
  type: sequence
  element_data_type: triangle3d
  number_of_elements: sphere3d.number_of_triangles
----

==== Padding

Padding is a member definition to represent (alignment) padding as a byte
stream.

[source,yaml]
----
name: padding1
type: padding
alignment_size: 32
----

Padding data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| alignment_size | integer | Yes | Alignment size
|===

Currently supported alignment_size attribute values are: 2, 4, 8 and 16 bytes.

[NOTE]
The padding is currently considered as required in the data stream.

==== Union

[yellow-background]*TODO: describe union*

== Semantic types

=== Constant

A constant is a data type to provide meaning (semantic value) to a single
predefined value. The value of a constant is typically not stored in a byte
stream but used at compile time.

[source,yaml]
----
name: maximum_number_of_back_traces
aliases: [AVRF_MAX_TRACES]
type: constant
description: Application verifier resource enumeration maximum number of back traces
urls: ['https://msdn.microsoft.com/en-us/library/bb432193(v=vs.85).aspx']
value: 13
----

Constant data type specfic attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| value | integer or string | Yes | Integer or string value that the constant represents
|===

=== Enumeration

An enumeration is a data type to provide meaning (semantic value) to one or more
predefined values.

[source,yaml]
----
name: handle_trace_operation_types
aliases: [eHANDLE_TRACE_OPERATIONS]
type: enumeration
description: Application verifier resource enumeration handle trace operation types
urls: ['https://msdn.microsoft.com/en-us/library/bb432251(v=vs.85).aspx']
values:
- name: OperationDbUnused
  number: 0
  description: Unused
- name: OperationDbOPEN
  number: 1
  description: Open (create) handle operation
- name: OperationDbCLOSE
  number: 2
  description: Close handle operation
- name: OperationDbBADREF
  number: 3
  description: Invalid handle operation
----

Enumeration value attributes:

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| aliases | list of strings | No | List of alternative names for the enumeration
| description | string | No | Description of the enumeration value
| name | string | Yes | Name the enumeration value maps to
| number | integer | Yes | Number the enumeration value maps to
|===

[yellow-background]*TODO: add description*

== Layout types

=== [[data_format]]Data format

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| attributes | mapping | No | Data type attributes +
See section: <<data_format_attributes,Data format attributes>>
| description | string | No | Description of the format
| layout | mapping | Yes | Format layout definition
| metadata | mapping | No | Metadata
| name | string | Yes | Name of the format
| type | string | Yes | Definition type +
See section: <<data_type_definition_types,Data type definition types>>
| urls | List of strings | No | List of URLS that contain more information about the format
|===

Example:

[source,yaml]
----
name: mdmp
type: format
description: Minidump file format
urls: ['https://msdn.microsoft.com/en-us/library/windows/desktop/ms680369(v=vs.85).aspx']
layout:
- file_header
----

==== [[data_format_attributes]]Data format attributes

[cols="1,1,1,5",options="header"]
|===
| Attribute name | Attribute type | Required | Description
| byte_order | string | No | Byte-order of the data type +
Valid options are: "big-endian", "little-endian", "native" +
The default is native
|===

[NOTE]
middle-endian is a valid byte-ordering but currently not supported.

=== Structure family

A structure family is a layout type to represent multiple generations
(versions) of the same structure.

[source,yaml]
----
name: group_descriptor
type: type-family
description: Group descriptor of Extended File System version 2, 3 and 4
runtime: group_descriptor_runtime
members:
- group_descriptor_ext2
- group_descriptor_ext4
----

:numbered!:
[appendix]
== References

`[YAML]`

[cols="1,5",options="header"]
|===
| Title: | YAML Ain’t Markup Language (YAML™)
| Version: | 1.2
| Data: | November 1, 2009
| URL: | http://yaml.org/spec/1.2/spec.html
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

